# Generated by Django 6.0 on 2026-04-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagements', '0002_pentestrequest_website_url'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NOVAAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engagement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nova_analysis', to='engagements.engagement')),
            ],
        ),
    ]
